import ApplyApi from './autogenerated/ApplyApi'
import ArticleApi from './autogenerated/ArticleApi'
import CommentApi from './autogenerated/CommentApi'
import HelpApi from './autogenerated/HelpApi'
import ImageApi from './autogenerated/ImageApi'
import LikeApi from './autogenerated/LikeApi'
import PostApi from './autogenerated/PostApi'
import RelationApi from './autogenerated/RelationApi'
import ReplyApi from './autogenerated/ReplyApi'
import SearchApi from './autogenerated/SearchApi'
import SuggestionApi from './autogenerated/SuggestionApi'
import TestApi from './autogenerated/TestApi'
import UserApi from './autogenerated/UserApi'

export {
  ApplyApi,
  ArticleApi,
  CommentApi,
  HelpApi,
  ImageApi,
  LikeApi,
  PostApi,
  RelationApi,
  ReplyApi,
  SearchApi,
  SuggestionApi,
  TestApi,
  UserApi
}
