import Taro from '@tarojs/taro'
import { UserApi as _UserApi } from '@/api/autogenerated'

const login = async () => {
  const code = (await Taro.login()).code
  return _UserApi.login({ code })
}
const UserApi = { ..._UserApi, login }

export * from '@/api/autogenerated'
export { UserApi }
