/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/user/update': {
    /**
     * 用户更新信息
     * @description 用户更新信息
     */
    put: operations['update']
  }
  '/survey/update': {
    /**
     * 更新问卷
     * @description 更新问卷
     */
    put: operations['update_1']
  }
  '/survey/section/update': {
    /**
     * 更新章节
     * @description 更新章节
     */
    put: operations['updateSection']
  }
  '/survey/option/update': {
    /**
     * 更新选项
     * @description 更新选项
     */
    put: operations['updateOption']
  }
  '/survey/issue/update': {
    /**
     * 更新问题
     * @description 更新问题
     */
    put: operations['updateIssue']
  }
  '/response/finish': {
    /**
     * 完成问卷
     * @description 完成问卷
     */
    put: operations['finishResponse']
  }
  '/post/share': {
    /**
     * 分享帖子
     * @description 分享帖子
     */
    put: operations['share']
  }
  '/comment/share': {
    /**
     * 分享评论
     * @description 分享评论
     */
    put: operations['share_1']
  }
  '/apply/handle': {
    /**
     * 处理好友申请
     * @description 处理好友申请
     */
    put: operations['handle']
  }
  '/user/send': {
    /**
     * 发送手机验证码
     * @description 发送手机验证码
     */
    post: operations['send']
  }
  '/survey/section/add': {
    /**
     * 添加章节
     * @description 添加章节
     */
    post: operations['addSection']
  }
  '/survey/option/add': {
    /**
     * 添加选项
     * @description 添加选项
     */
    post: operations['addOption']
  }
  '/survey/issue/add': {
    /**
     * 添加问题
     * @description 添加问题
     */
    post: operations['addIssue']
  }
  '/survey/add': {
    /**
     * 添加问卷
     * @description 添加问卷
     */
    post: operations['add']
  }
  '/suggestion/add': {
    /**
     * 添加意见反馈
     * @description 添加意见反馈
     */
    post: operations['addSuggestion']
  }
  '/response/start': {
    /**
     * 开始作答问卷
     * @description 开始作答问卷
     */
    post: operations['startResponse']
  }
  '/response/do': {
    /**
     * 作答/修改问卷题目
     * @description 作答/修改问卷题目
     */
    post: operations['doResponse']
  }
  '/reply/add': {
    /**
     * 添加回复
     * @description 添加回复
     */
    post: operations['addReply']
  }
  '/question/add': {
    /**
     * 添加问题
     * @description 添加问题
     */
    post: operations['add_1']
  }
  '/post/add': {
    /**
     * 添加帖子
     * @description 添加帖子
     */
    post: operations['addPost']
  }
  '/like/do': {
    /**
     * 点赞
     * @description 点赞
     */
    post: operations['like']
  }
  '/images': {
    /**
     * 上传多张图片
     * @description 上传多张图片
     */
    post: operations['uploadImages']
  }
  '/image': {
    /**
     * 上传图片
     * @description 上传图片
     */
    post: operations['uploadImage']
  }
  '/comment/add': {
    /**
     * 评论 type 1为帖子 2为文章
     * @description 评论 type 1为帖子 2为文章
     */
    post: operations['comment']
  }
  '/article/add': {
    /**
     * 添加文章
     * @description 添加文章
     */
    post: operations['add_2']
  }
  '/apply/do': {
    /**
     * 此用户申请添加指定用户为好友
     * @description 此用户申请添加指定用户为好友
     */
    post: operations['apply']
  }
  '/user/verify': {
    /**
     * 验证手机验证码并登录
     * @description 验证手机验证码并登录
     */
    get: operations['verify']
  }
  '/user/login': {
    /**
     * 用户微信登录
     * @description 用户微信登录
     */
    get: operations['login']
  }
  '/user/info': {
    /**
     * 获取用户信息
     * @description 获取用户信息
     */
    get: operations['info']
  }
  '/user/id': {
    /**
     * 获取指定id的用户信息
     * @description 获取指定id的用户信息
     */
    get: operations['info_1']
  }
  '/user/check': {
    /**
     * 检查登录态
     * @description 检查登录态
     */
    get: operations['check']
  }
  '/user/authLogin': {
    /**
     * 用户手机号登录
     * @description 用户手机号登录
     */
    get: operations['authLogin']
  }
  '/test/hello': {
    get: operations['hello']
  }
  '/test/502': {
    get: operations['test502']
  }
  '/test/500': {
    get: operations['test500']
  }
  '/test/404': {
    get: operations['test404']
  }
  '/test/403': {
    get: operations['test403']
  }
  '/test/401': {
    get: operations['test401']
  }
  '/test/400': {
    get: operations['test400']
  }
  '/test/200': {
    get: operations['test200']
  }
  '/survey/section/get': {
    /**
     * 获取章节
     * @description 获取章节
     */
    get: operations['getSection']
  }
  '/survey/option/get': {
    /**
     * 获取选项
     * @description 获取选项
     */
    get: operations['getOption']
  }
  '/survey/issue/get': {
    /**
     * 获取问题
     * @description 获取问题
     */
    get: operations['getIssue']
  }
  '/survey/get': {
    /**
     * 获取问卷
     * @description 获取问卷
     */
    get: operations['get']
  }
  '/suggestion/get': {
    /**
     * 获取建议列表
     * @description 获取建议列表
     */
    get: operations['getSuggestions']
  }
  '/search/users': {
    /**
     * 根据关键词搜索用户
     * @description 根据关键词搜索用户
     */
    get: operations['getUserList']
  }
  '/search/posts': {
    /**
     * 根据关键词搜索帖子
     * @description 根据关键词搜索帖子
     */
    get: operations['getPosts']
  }
  '/search/friendsPosts': {
    /**
     * 根据关键词搜索好友的帖子
     * @description 根据关键词搜索好友的帖子
     */
    get: operations['getFriendsPosts']
  }
  '/search/articles': {
    get: operations['getArticles']
  }
  '/response/res': {
    /**
     * 获取问卷作答结果
     * @description 获取问卷作答结果
     */
    get: operations['getResult']
  }
  '/response/get': {
    /**
     * 获取当前用户正在作答的问卷记录
     * @description 获取当前用户正在作答的问卷记录
     */
    get: operations['getResponse']
  }
  '/response/getSections': {
    /**
     * 获取问卷包含的所有章节
     * @description 获取问卷包含的所有章节
     */
    get: operations['get_1']
  }
  '/response/getLatest': {
    /**
     * 获取用户最近已完成的问卷作答记录
     * @description 获取用户最近已完成的问卷作答记录
     */
    get: operations['getLatest']
  }
  '/response/getIssues': {
    /**
     * 获取章节包含的问题+选项列表
     * @description 获取章节包含的问题+选项列表
     */
    get: operations['get_2']
  }
  '/response/getAll': {
    /**
     * 获取用户的所有已完成的问卷作答记录
     * @description 获取用户的所有已完成的问卷作答记录
     */
    get: operations['getSurveyData']
  }
  '/reply/get': {
    /**
     * 获取回复列表
     * @description 获取回复列表
     */
    get: operations['getList']
  }
  '/relation/getFriendList': {
    /**
     * 获取好友列表
     * @description 获取好友列表
     */
    get: operations['getFriendList']
  }
  '/question/get': {
    /**
     * 问答搜索
     *  输入用户提问的句子，返回包含关键词的问题列表，如果没有找到关键词则返回空列表
     * @description 问答搜索
     *  输入用户提问的句子，返回包含关键词的问题列表，如果没有找到关键词则返回空列表
     */
    get: operations['get_3']
  }
  '/question/getRand': {
    /**
     * 获取随机问题
     *  猜你想问？
     * @description 获取随机问题
     *  猜你想问？
     */
    get: operations['getRand']
  }
  '/question/getDetail': {
    /**
     * 获取问答全部内容
     * @description 获取问答全部内容
     */
    get: operations['getDetail']
  }
  '/post/get': {
    /**
     * 获取帖子列表
     * @description 获取帖子列表
     */
    get: operations['getList_1']
  }
  '/post/getFriendsPost': {
    /**
     * 获取好友的帖子列表
     * @description 获取好友的帖子列表
     */
    get: operations['getFriendsPost']
  }
  '/post/getDetail': {
    /**
     * 获取帖子详情
     * @description 获取帖子详情
     */
    get: operations['getDetail_1']
  }
  '/post/getByUser': {
    /**
     * 获取指定用户的帖子列表
     *  用于查看个人主页
     * @description 获取指定用户的帖子列表
     *  用于查看个人主页
     */
    get: operations['getByUser']
  }
  '/msg/get': {
    /**
     * 获取指定好友消息列表
     * @description 获取指定好友消息列表
     */
    get: operations['get_4']
  }
  '/help/get': {
    /**
     * 获取简要常见问题
     * @description 获取简要常见问题
     */
    get: operations['getSuggestions_1']
  }
  '/help/getDetail': {
    /**
     * 获取常见问题详情
     * @description 获取常见问题详情
     */
    get: operations['getDetail_2']
  }
  '/comment/get': {
    /**
     * 获取评论列表
     * @description 获取评论列表
     */
    get: operations['getList_2']
  }
  '/comment/getDetail': {
    /**
     * 获取评论详情
     * @description 获取评论详情
     */
    get: operations['getDetail_3']
  }
  '/article/get': {
    /**
     * 获取文章列表
     * @description 获取文章列表
     */
    get: operations['getList_3']
  }
  '/apply/getApplyList': {
    /**
     * 获取好友申请列表
     * @description 获取好友申请列表
     */
    get: operations['getApplyList']
  }
  '/user/delete': {
    /**
     * 删除用户
     * @description 删除用户
     */
    delete: operations['deleteUser']
  }
  '/survey/section/del': {
    /**
     * 删除章节
     * @description 删除章节
     */
    delete: operations['delSection']
  }
  '/survey/option/del': {
    /**
     * 删除选项
     * @description 删除选项
     */
    delete: operations['delOption']
  }
  '/survey/issue/del': {
    /**
     * 删除问题
     * @description 删除问题
     */
    delete: operations['delIssue']
  }
  '/survey/del': {
    /**
     * 删除问卷
     * @description 删除问卷
     */
    delete: operations['del']
  }
  '/reply/del': {
    /**
     * 删除回复
     * @description 删除回复
     */
    delete: operations['delReply']
  }
  '/relation/del': {
    /**
     * 删除好友
     * @description 删除好友
     */
    delete: operations['deleteFriend']
  }
  '/post/del': {
    /**
     * 删除帖子
     * @description 删除帖子
     */
    delete: operations['delete']
  }
  '/msg/delete': {
    /**
     * 删除消息
     * @description 删除消息
     */
    delete: operations['delete_1']
  }
  '/like/undo': {
    /**
     * 取消点赞
     * @description 取消点赞
     */
    delete: operations['unlike']
  }
  '/comment/del': {
    /**
     * 删除评论
     * @description 删除评论
     */
    delete: operations['delete_2']
  }
  '/ws': {
    /**
     * 连接到Websocket
     * @description 只提供使用示例，无法在swagger-ui中测试，需要使用WebSocket
     */
    get: {
      parameters: {
        header: {
          Authorization: string
        }
      }
      responses: {
        /** @description Current user is connected to WebSocket */
        OK: {
          content: never
        }
      }
    }
  }
  'Send message': {
    /**
     * 用户间通讯
     * @description 只提供使用示例，无法在swagger-ui中测试，需要使用WebSocket
     */
    get: {
      /** @description Message */
      requestBody?: {
        content: {
          'application/json': {
            /** Format: int32 */
            toUserId?: number
            content?: string
          }
        }
      }
      responses: {
        /** @description Successfully sent */
        OK: {
          content: never
        }
      }
    }
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    /** @description 通用返回结果 */
    ResultObject: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: Record<string, never>
      /** @description 信息 */
      msg?: string
    }
    /** @description 更新用户请求 */
    UpdateUserRequest: {
      /** @description 名字 */
      name?: string
      /**
       * Format: int32
       * @description 性别
       */
      gender?: number
      /** @description 国籍 */
      nation?: string
      /**
       * Format: int32
       * @description 证件类型
       */
      documentType?: number
      /** @description 证件号码 */
      documentNumber?: string
      /** @description 证件有效期 */
      documentValidDate?: string
      /** @description 工作 */
      job?: string
      /** @description 地址 */
      address?: string
      /** @description 头像url */
      avatar?: string
    }
    /** @description 通用返回结果 */
    ResultUser: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['User']
      /** @description 信息 */
      msg?: string
    }
    /** @description 用户 */
    User: {
      /**
       * Format: int64
       * @description 用户 ID
       */
      id?: number
      /**
       * Format: int32
       * @description 用户类型
       */
      type?: number
      /** @description openId */
      openId?: string
      /**
       * Format: date-time
       * @description 创建时间
       */
      createTime?: string
      /**
       * Format: date-time
       * @description 删除时间
       */
      deleteTime?: string
      /** @description 名字 */
      name?: string
      /**
       * Format: int32
       * @description 性别
       */
      gender?: number
      /** @description 是否实名认证 */
      isVerified?: boolean
      /** @description 国籍 */
      nation?: string
      /**
       * Format: int32
       * @description 证件类型
       */
      documentType?: number
      /** @description 证件号码 */
      documentNumber?: string
      /** @description 证件有效期 */
      documentValidDate?: string
      /** @description 手机号 */
      phone?: string
      /** @description 工作 */
      job?: string
      /** @description 地址 */
      address?: string
      /** @description 头像url */
      avatar?: string
    }
    /** @description 更新问卷请求 */
    UpdateSurveyRequest: {
      /**
       * Format: int64
       * @description 问卷 ID
       */
      id?: number
      /** @description 问卷标题 */
      title?: string
      /** @description 问卷描述 */
      description?: string
    }
    /** @description 通用返回结果 */
    ResultSurvey: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['Survey']
      /** @description 信息 */
      msg?: string
    }
    /** @description 问卷 */
    Survey: {
      /**
       * Format: int64
       * @description 问卷 ID
       */
      id?: number
      /** @description 问卷标题 */
      title?: string
      /** @description 问卷描述 */
      description?: string
      /**
       * Format: int64
       * @description 章节数
       */
      sections?: number
    }
    /** @description 更改章节请求 */
    UpdateSectionRequest: {
      /**
       * Format: int64
       * @description 部分 ID
       */
      id?: number
      /** @description 部分标题 */
      title?: string
      /** @description 部分描述 */
      description?: string
    }
    /** @description 通用返回结果 */
    ResultSection: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['Section']
      /** @description 信息 */
      msg?: string
    }
    /** @description 问卷章节 */
    Section: {
      /**
       * Format: int64
       * @description 章节 ID
       */
      id?: number
      /**
       * Format: int64
       * @description 问卷id
       */
      surveyId?: number
      /** @description 章节标题 */
      title?: string
      /** @description 章节描述 */
      description?: string
      /**
       * Format: int64
       * @description 问题数
       */
      questions?: number
    }
    /** @description 更改选项请求 */
    UpdateOptionRequest: {
      /**
       * Format: int64
       * @description 选项 ID
       */
      id?: number
      /** @description 选项内容 */
      content?: string
      /**
       * Format: double
       * @description 选项分数
       */
      score?: number
    }
    /** @description 问卷问题选项 */
    Options: {
      /**
       * Format: int64
       * @description 选项 ID
       */
      id?: number
      /**
       * Format: int64
       * @description 问题 ID
       */
      issueId?: number
      /** @description 选项内容 */
      content?: string
      /**
       * Format: double
       * @description 选项分数
       */
      score?: number
    }
    /** @description 通用返回结果 */
    ResultOptions: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['Options']
      /** @description 信息 */
      msg?: string
    }
    /** @description 更改问卷问题请求 */
    UpdateIssueRequest: {
      /**
       * Format: int64
       * @description 问题 ID
       */
      id?: number
      /** @description 问题内容 */
      content?: string
      /**
       * Format: double
       * @description 权重
       */
      weight?: number
    }
    /** @description 问卷问题 */
    Issue: {
      /**
       * Format: int64
       * @description 问卷 ID
       */
      id?: number
      /**
       * Format: int64
       * @description 部分 ID
       */
      sectionId?: number
      /** @description 问题内容 */
      content?: string
      /**
       * Format: int32
       * @description 问题类型
       */
      type?: number
      /**
       * Format: int64
       * @description 问题选项数
       */
      options?: number
      /**
       * Format: double
       * @description 权重
       */
      weight?: number
    }
    /** @description 通用返回结果 */
    ResultIssue: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['Issue']
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultBoolean: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: boolean
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultSmsResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['SmsResponse']
      /** @description 信息 */
      msg?: string
    }
    SmsResponse: {
      success?: boolean
      msg?: string
    }
    /** @description 添加章节请求 */
    AddSectionRequest: {
      /**
       * Format: int64
       * @description 问卷id
       */
      surveyId?: number
      /** @description 部分标题 */
      title?: string
      /** @description 部分描述 */
      description?: string
    }
    /** @description 添加选项请求 */
    AddOptionRequest: {
      /**
       * Format: int64
       * @description 问题 ID
       */
      issueId?: number
      /** @description 选项内容 */
      content?: string
      /**
       * Format: double
       * @description 选项分数
       */
      score?: number
    }
    /** @description 添加问题请求 */
    AddIssueRequest: {
      /**
       * Format: int64
       * @description 部分 ID
       */
      sectionId?: number
      /** @description 问题内容 */
      content?: string
      /**
       * Format: int32
       * @description 问题类型
       *  1：选择
       *  2：填空
       */
      type?: number
      /**
       * Format: double
       * @description 权重
       */
      weight?: number
    }
    /** @description 上传问卷接口请求 */
    AddSurveyRequest: {
      /** @description 问卷标题 */
      title?: string
      /** @description 问卷描述 */
      description?: string
    }
    /** @description 上传意见反馈请求 */
    AddSuggestionRequest: {
      /** @description 标题 */
      title?: string
      /** @description 内容 */
      content?: string
      /** @description 图片 */
      image?: string
      /**
       * Format: int32
       * @description 类型
       */
      type?: number
    }
    /** @description 通用返回结果 */
    ResultSurveyData: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['SurveyData']
      /** @description 信息 */
      msg?: string
    }
    /** @description 用户填写问卷信息 */
    SurveyData: {
      /**
       * Format: int64
       * @description ID
       */
      id?: number
      /**
       * Format: int64
       * @description 用户 ID
       */
      userId?: number
      /**
       * Format: int64
       * @description 问卷 ID
       */
      surveyId?: number
      /**
       * Format: int32
       * @description 问卷状态
       *  0: 未开始
       *  1: 进行中
       *  2: 已完成
       */
      status?: number
      /**
       * Format: date-time
       * @description 回答创建时间
       */
      createTime?: string
      /**
       * Format: date-time
       * @description 回答更新时间
       */
      updateTime?: string
      /**
       * Format: int64
       * @description 最后一次回答的问题
       *  0: 未开始
       */
      lastIssue?: number
    }
    /** @description 添加或修改问卷结果请求 */
    DoSurveyRequest: {
      /**
       * Format: int64
       * @description 问题 ID
       */
      issueId?: number
      /**
       * Format: int64
       * @description 选项 ID
       */
      optionId?: number
      /** @description 答案 */
      answer?: string
    }
    /** @description 用户回答题目信息 */
    IssueData: {
      /**
       * Format: int64
       * @description 回答 ID
       */
      id?: number
      /**
       * Format: int64
       * @description 用户填写问卷信息 ID
       */
      responseId?: number
      /**
       * Format: int64
       * @description 问题 ID
       */
      issueId?: number
      /**
       * Format: int64
       * @description 选项 ID
       */
      optionId?: number
      /** @description 回答内容 */
      answer?: string
    }
    /** @description 通用返回结果 */
    ResultIssueData: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['IssueData']
      /** @description 信息 */
      msg?: string
    }
    /** @description 发布回复请求 */
    AddReplyRequest: {
      /** @description 回复内容 */
      content?: string
      /**
       * Format: int64
       * @description 评论id
       */
      commentId?: number
      /**
       * Format: int64
       * @description 被回复的id
       *  如果此回复是指向另一个回复的，则字段存在，否则为null
       */
      toId?: number
    }
    /** @description 用户视角评论信息 */
    ReplyResponse: {
      /**
       * Format: int64
       * @description id
       */
      id?: number
      /**
       * Format: int64
       * @description 评论 id
       */
      commentId?: number
      /**
       * Format: int64
       * @description 被回复的 id
       *  如果此回复是指向另一个回复的，则字段存在，否则为null
       */
      toId?: number
      /**
       * Format: int64
       * @description 用户 id
       */
      userId?: number
      /**
       * @description 被回复的用户 id
       *  如果此回复是指向另一个回复的，则字段存在，否则为null
       */
      toUserId?: string
      /**
       * Format: date-time
       * @description 创建时间
       */
      createTime?: string
      /**
       * Format: date-time
       * @description 删除时间
       */
      deleteTime?: string
      /** @description 内容 */
      content?: string
      /**
       * Format: int64
       * @description 点赞数
       */
      likes?: number
      /** @description 用户名字 */
      name?: string
      /** @description 用户头像 */
      avatar?: string
      /**
       * @description 被回复的用户名字
       *  如果此回复是指向另一个回复的，则字段存在，否则为null
       */
      toName?: string
      /** @description 是否点赞 */
      isLiked?: boolean
    }
    /** @description 通用返回结果 */
    ResultReplyResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['ReplyResponse']
      /** @description 信息 */
      msg?: string
    }
    /** @description 添加问答请求 */
    AddQuestionRequest: {
      /** @description 问题内容 */
      content?: string
      /** @description 问题答案 */
      answer?: string
    }
    /** @description 发布帖子请求 */
    AddPostRequest: {
      /** @description 内容 */
      content?: string
      /** @description 图片 */
      image?: string
    }
    /** @description 用户视角帖子信息 */
    PostResponse: {
      /**
       * Format: int64
       * @description 帖子 ID
       */
      id?: number
      /**
       * Format: date-time
       * @description 创建时间
       */
      createTime?: string
      /**
       * Format: date-time
       * @description 更新时间
       */
      updateTime?: string
      /**
       * Format: date-time
       * @description 删除时间
       */
      deleteTime?: string
      /** @description 内容 */
      content?: string
      /**
       * Format: int64
       * @description 发布用户 ID
       */
      userId?: number
      /** @description 图片 */
      image?: string
      /**
       * Format: int64
       * @description 点赞数
       */
      likes?: number
      /**
       * Format: int64
       * @description 评论数
       */
      comments?: number
      /**
       * Format: int64
       * @description 分享数
       */
      shares?: number
      /** @description 发帖用户名字 */
      name?: string
      /** @description 发帖用户头像 */
      avatar?: string
      /** @description 是否点赞 */
      isLiked?: boolean
    }
    /** @description 通用返回结果 */
    ResultPostResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['PostResponse']
      /** @description 信息 */
      msg?: string
    }
    /** @description 改变点赞状态请求 */
    DoLikeRequest: {
      /**
       * Format: int64
       * @description 对象id
       */
      objId?: number
      /**
       * Format: int32
       * @description 类型
       *  1：帖子 2：评论 3：回复 4：文章
       */
      type?: number
    }
    /** @description 通用返回结果 */
    ResultListString: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: string[]
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultString: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: string
      /** @description 信息 */
      msg?: string
    }
    /** @description 发布评论请求 */
    AddCommentRequest: {
      /** @description 评论内容 */
      content?: string
      /**
       * Format: int64
       * @description 对象id
       *  文章id或帖子id
       */
      objId?: number
      /**
       * Format: int32
       * @description 评论类型
       *  1: 帖子
       *  2: 文章
       */
      type?: number
    }
    /** @description 用户视角评论信息 */
    CommentResponse: {
      /**
       * Format: int64
       * @description 评论 ID
       */
      id?: number
      /**
       * Format: int64
       * @description 对象 ID
       *  文章id或帖子id
       */
      objId?: number
      /**
       * Format: int64
       * @description 楼层
       */
      floor?: number
      /**
       * Format: int64
       * @description 用户 ID
       */
      userId?: number
      /**
       * Format: date-time
       * @description 创建时间
       */
      createTime?: string
      /**
       * Format: date-time
       * @description 删除时间
       */
      deleteTime?: string
      /** @description 内容 */
      content?: string
      /**
       * Format: int64
       * @description 点赞数
       */
      likes?: number
      /**
       * Format: int64
       * @description 回复数
       */
      replies?: number
      /**
       * Format: int64
       * @description 分享数
       */
      shares?: number
      /** @description 用户名字 */
      name?: string
      /** @description 用户头像 */
      avatar?: string
      /** @description 是否点赞 */
      isLiked?: boolean
    }
    /** @description 通用返回结果 */
    ResultCommentResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['CommentResponse']
      /** @description 信息 */
      msg?: string
    }
    /** @description 发布文章请求 */
    AddArticleRequest: {
      /**
       * Format: int32
       * @description 文章类型
       */
      type?: number
      /** @description 文章标题 */
      title?: string
      /** @description 文章内容 */
      content?: string
      /** @description 图片 */
      image?: string
      /** @description 链接 */
      link?: string
    }
    /** @description 用户视角帖子信息 */
    ArticleResponse: {
      /**
       * Format: int64
       * @description 文章 ID
       */
      id?: number
      /**
       * Format: date-time
       * @description 创建时间
       */
      createTime?: string
      /**
       * Format: int32
       * @description 文章类型
       */
      type?: number
      /**
       * Format: int64
       * @description 发布用户 ID
       */
      userId?: number
      /** @description 文章标题 */
      title?: string
      /** @description 文章内容 */
      content?: string
      /** @description 图片 */
      image?: string
      /** @description 链接 */
      link?: string
      /**
       * Format: int64
       * @description 点赞数
       */
      likes?: number
      /**
       * Format: int64
       * @description 评论数
       */
      comments?: number
      /**
       * Format: int64
       * @description 分享数
       */
      shares?: number
      /** @description 发布用户名字 */
      name?: string
      /** @description 是否点赞 */
      isLiked?: boolean
    }
    /** @description 通用返回结果 */
    ResultArticleResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['ArticleResponse']
      /** @description 信息 */
      msg?: string
    }
    /** @description 登录响应 */
    LoginResponse: {
      /** @description token */
      token?: string
      /**
       * Format: int64
       * @description 用户 ID
       */
      userId?: number
      /**
       * Format: int32
       * @description 用户类型
       */
      type?: number
    }
    /** @description 通用返回结果 */
    ResultVerificationResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['VerificationResponse']
      /** @description 信息 */
      msg?: string
    }
    /** @description 验证码响应 */
    VerificationResponse: {
      /** @description 验证码是否正确 */
      correct?: boolean
      /**
       * @description 授权码，如果验证码正确则返回授权码，否则为null
       *  用于下次登录时 传入授权码获取登录响应
       *  授权码
       */
      authCode?: string
      response?: components['schemas']['LoginResponse']
    }
    /** @description 通用返回结果 */
    ResultLoginResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['LoginResponse']
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultListSection: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['Section'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultListOptions: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['Options'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultListIssue: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['Issue'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultListSurvey: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['Survey'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultListSuggestion: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['Suggestion'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 意见反馈 */
    Suggestion: {
      /**
       * Format: int64
       * @description 意见反馈 ID
       */
      id?: number
      /** @description 标题 */
      title?: string
      /** @description 内容 */
      content?: string
      /** @description 图片 */
      image?: string
      /**
       * Format: int64
       * @description 反馈用户 ID
       */
      userId?: number
      /**
       * Format: date-time
       * @description 创建时间
       */
      createTime?: string
    }
    /** @description 搜索用户列表用户视角简要信息 */
    BriefUserResponse: {
      /**
       * Format: int64
       * @description 用户 ID
       */
      id?: number
      /**
       * Format: int32
       * @description 用户类型
       */
      type?: number
      /** @description 用户名 */
      name?: string
      /** @description 头像 */
      avatar?: string
      /** @description 是否已添加 */
      isFriend?: boolean
    }
    /** @description 通用返回结果 */
    ResultListBriefUserResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['BriefUserResponse'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultListPostResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['PostResponse'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultListArticleResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['ArticleResponse'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 问卷结果内容 */
    ResultResponse: {
      /** Format: double */
      score?: number
    }
    /** @description 通用返回结果 */
    ResultResultResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['ResultResponse']
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultSurveyResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['SurveyResponse']
      /** @description 信息 */
      msg?: string
    }
    /** @description 章节信息 */
    SectionDto: {
      /**
       * Format: int64
       * @description 章节 ID
       */
      id?: number
      /**
       * Format: int32
       * @description 章节序号
       *  从1开始递增
       */
      serial?: number
      /** @description 章节标题 */
      title?: string
      /** @description 章节描述 */
      description?: string
      /**
       * Format: int64
       * @description 问题数
       */
      questions?: number
    }
    /** @description 问卷详细内容 */
    SurveyResponse: {
      /**
       * Format: int64
       * @description 问卷 ID
       */
      id?: number
      /** @description 问卷标题 */
      title?: string
      /** @description 问卷描述 */
      description?: string
      /**
       * Format: int64
       * @description 章节数
       */
      sections?: number
      /** @description 详细章节信息 */
      section?: components['schemas']['SectionDto'][]
    }
    /** @description 详细问题信息 */
    IssueResponse: {
      /**
       * Format: int64
       * @description 问题 ID
       */
      id?: number
      /**
       * Format: int32
       * @description 问题序号
       *  从1开始递增
       */
      serial?: number
      /** @description 问题内容 */
      content?: string
      /**
       * Format: int32
       * @description 问题类型
       */
      type?: number
      /**
       * Format: int64
       * @description 问题选项数
       */
      options?: number
      /** @description 问题选项详细信息 */
      option?: components['schemas']['OptionsDto'][]
    }
    /** @description 选项信息 */
    OptionsDto: {
      /**
       * Format: int64
       * @description 选项 ID
       */
      id?: number
      /**
       * Format: int64
       * @description 问题 ID
       */
      issueId?: number
      /**
       * Format: int32
       * @description 选项序号
       *  从1开始递增
       */
      serial?: number
      /** @description 选项内容 */
      content?: string
      /**
       * Format: double
       * @description 选项分数
       */
      score?: number
    }
    /** @description 通用返回结果 */
    ResultListIssueResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['IssueResponse'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultListSurveyData: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['SurveyData'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultListReplyResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['ReplyResponse'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 用户视角好友简要信息 */
    BriefFriendResponse: {
      /**
       * Format: int64
       * @description 用户 ID
       */
      id?: number
      /**
       * Format: int32
       * @description 用户类型
       */
      type?: number
      /** @description 用户名 */
      name?: string
      /** @description 头像 */
      avatar?: string
    }
    /** @description 通用返回结果 */
    ResultListBriefFriendResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['BriefFriendResponse'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 自助问答问题 */
    Question: {
      /**
       * Format: int64
       * @description 问题 ID
       */
      id?: number
      /** @description 问题内容 */
      content?: string
      /** @description 答案 */
      answer?: string
    }
    /** @description 通用返回结果 */
    ResultListQuestion: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['Question'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultQuestion: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['Question']
      /** @description 信息 */
      msg?: string
    }
    /** @description 简要帖子信息 */
    BriefPostResponse: {
      /**
       * Format: int64
       * @description 帖子 ID
       */
      id?: number
      /** @description 内容 */
      content?: string
      /** @description 图片 */
      image?: string
    }
    /** @description 通用返回结果 */
    ResultListBriefPostResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['BriefPostResponse'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 消息响应 */
    MessageResponse: {
      /**
       * Format: int64
       * @description 消息 ID
       */
      id?: number
      /**
       * Format: int64
       * @description 发送用户 ID
       */
      userId?: number
      /** @description 发送用户名 */
      name?: string
      /** @description 发送用户头像 */
      avatar?: string
      /**
       * Format: int64
       * @description 接收用户 ID
       */
      toUserId?: number
      /** @description 接收用户名 */
      toName?: string
      /** @description 接收用户头像 */
      toAvatar?: string
      /** @description 内容 */
      content?: string
      /**
       * Format: date-time
       * @description 创建时间
       */
      createTime?: string
    }
    /** @description 通用返回结果 */
    ResultListMessageResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['MessageResponse'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 简要常见问题信息 */
    BriefHelpResponse: {
      /**
       * Format: int64
       * @description 常见问题 ID
       */
      id?: number
      /** @description 标题 */
      title?: string
    }
    /** @description 通用返回结果 */
    ResultListBriefHelpResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['BriefHelpResponse'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 常见问题 */
    Help: {
      /**
       * Format: int64
       * @description 常见问题 ID
       */
      id?: number
      /** @description 标题 */
      title?: string
      /** @description 内容 */
      content?: string
      /** @description 图片 */
      image?: string
      /**
       * Format: int64
       * @description 发布用户 ID
       */
      userId?: number
      /**
       * Format: date-time
       * @description 创建时间
       */
      createTime?: string
    }
    /** @description 通用返回结果 */
    ResultHelp: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      data?: components['schemas']['Help']
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultListCommentResponse: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['CommentResponse'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 联查申请添加好友信息 */
    ApplyDto: {
      /**
       * Format: int64
       * @description 申请 ID
       */
      id?: number
      /**
       * Format: int64
       * @description 发送好友申请的用户 ID
       */
      userId?: number
      /**
       * Format: date-time
       * @description 创建时间
       */
      createTime?: string
      /** @description 用户名 */
      name?: string
      /** @description 用户头像 */
      avatar?: string
    }
    /** @description 通用返回结果 */
    ResultListApplyDto: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /** @description 返回数据 */
      data?: components['schemas']['ApplyDto'][]
      /** @description 信息 */
      msg?: string
    }
    /** @description 通用返回结果 */
    ResultInteger: {
      /**
       * Format: int32
       * @description 代码
       */
      code?: number
      /**
       * Format: int32
       * @description 返回数据
       */
      data?: number
      /** @description 信息 */
      msg?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  /**
   * 用户更新信息
   * @description 用户更新信息
   */
  update: {
    /** @description 更新信息 */
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserRequest']
      }
    }
    responses: {
      /** @description 更新结果 */
      200: {
        content: {
          'application/json': components['schemas']['ResultUser']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 更新问卷
   * @description 更新问卷
   */
  update_1: {
    /** @description 更新问卷请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateSurveyRequest']
      }
    }
    responses: {
      /** @description 问卷 */
      200: {
        content: {
          '*/*': components['schemas']['ResultSurvey']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 更新章节
   * @description 更新章节
   */
  updateSection: {
    /** @description 更新章节请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateSectionRequest']
      }
    }
    responses: {
      /** @description 章节 */
      200: {
        content: {
          '*/*': components['schemas']['ResultSection']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 更新选项
   * @description 更新选项
   */
  updateOption: {
    /** @description 更新选项请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateOptionRequest']
      }
    }
    responses: {
      /** @description 选项 */
      200: {
        content: {
          '*/*': components['schemas']['ResultOptions']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 更新问题
   * @description 更新问题
   */
  updateIssue: {
    /** @description 更新问题请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateIssueRequest']
      }
    }
    responses: {
      /** @description 问题 */
      200: {
        content: {
          '*/*': components['schemas']['ResultIssue']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 完成问卷
   * @description 完成问卷
   */
  finishResponse: {
    responses: {
      /** @description 完成结果 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 分享帖子
   * @description 分享帖子
   */
  share: {
    parameters: {
      query: {
        /** @description 帖子id */
        postId: number
      }
    }
    responses: {
      /** @description 数据库修改是否成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 分享评论
   * @description 分享评论
   */
  share_1: {
    parameters: {
      query: {
        /** @description 评论id */
        commentId: number
      }
    }
    responses: {
      /** @description 数据库修改是否成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 处理好友申请
   * @description 处理好友申请
   */
  handle: {
    parameters: {
      query: {
        /** @description 申请id */
        applyId: number
        /** @description 是否同意 */
        decision: boolean
      }
    }
    responses: {
      /** @description 是否处理成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 发送手机验证码
   * @description 发送手机验证码
   */
  send: {
    parameters: {
      query: {
        /** @description 手机号 */
        phone: string
      }
    }
    responses: {
      /** @description 是否发送成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultSmsResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 添加章节
   * @description 添加章节
   */
  addSection: {
    /** @description 添加章节请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['AddSectionRequest']
      }
    }
    responses: {
      /** @description 章节 */
      200: {
        content: {
          '*/*': components['schemas']['ResultSection']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 添加选项
   * @description 添加选项
   */
  addOption: {
    /** @description 添加选项请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['AddOptionRequest']
      }
    }
    responses: {
      /** @description 选项 */
      200: {
        content: {
          '*/*': components['schemas']['ResultOptions']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 添加问题
   * @description 添加问题
   */
  addIssue: {
    /** @description 添加问题请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['AddIssueRequest']
      }
    }
    responses: {
      /** @description 问题 */
      200: {
        content: {
          '*/*': components['schemas']['ResultIssue']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 添加问卷
   * @description 添加问卷
   */
  add: {
    /** @description 添加问卷请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['AddSurveyRequest']
      }
    }
    responses: {
      /** @description 问卷 */
      200: {
        content: {
          '*/*': components['schemas']['ResultSurvey']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 添加意见反馈
   * @description 添加意见反馈
   */
  addSuggestion: {
    /** @description 添加意见反馈请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['AddSuggestionRequest']
      }
    }
    responses: {
      /** @description 是否添加成功 */
      200: {
        content: {
          'application/json': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 开始作答问卷
   * @description 开始作答问卷
   */
  startResponse: {
    parameters: {
      query: {
        /** @description 问卷 ID */
        surveyId: number
      }
    }
    responses: {
      /** @description 问卷作答记录 */
      200: {
        content: {
          '*/*': components['schemas']['ResultSurveyData']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 作答/修改问卷题目
   * @description 作答/修改问卷题目
   */
  doResponse: {
    /** @description 作答请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['DoSurveyRequest']
      }
    }
    responses: {
      /** @description 作答结果 */
      200: {
        content: {
          '*/*': components['schemas']['ResultIssueData']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 添加回复
   * @description 添加回复
   */
  addReply: {
    /** @description 添加回复请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['AddReplyRequest']
      }
    }
    responses: {
      /** @description 是否添加成功 */
      200: {
        content: {
          'application/json': components['schemas']['ResultReplyResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 添加问题
   * @description 添加问题
   */
  add_1: {
    /** @description 添加问题请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['AddQuestionRequest']
      }
    }
    responses: {
      /** @description 是否添加成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 添加帖子
   * @description 添加帖子
   */
  addPost: {
    /** @description 添加帖子请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['AddPostRequest']
      }
    }
    responses: {
      /** @description 是否添加成功 */
      200: {
        content: {
          'application/json': components['schemas']['ResultPostResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 点赞
   * @description 点赞
   */
  like: {
    /** @description 点赞请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['DoLikeRequest']
      }
    }
    responses: {
      /** @description 是否点赞成功 */
      200: {
        content: {
          'application/json': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 上传多张图片
   * @description 上传多张图片
   */
  uploadImages: {
    /** @description 文件 */
    requestBody: {
      content: {
        'application/json': {
          file?: string[]
        }
      }
    }
    responses: {
      /** @description 图片地址 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListString']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 上传图片
   * @description 上传图片
   */
  uploadImage: {
    /** @description 文件 */
    requestBody: {
      content: {
        'application/json': {
          /** Format: binary */
          file?: string
        }
      }
    }
    responses: {
      /** @description 图片地址 */
      200: {
        content: {
          '*/*': components['schemas']['ResultString']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 评论 type 1为帖子 2为文章
   * @description 评论 type 1为帖子 2为文章
   */
  comment: {
    /** @description 评论请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['AddCommentRequest']
      }
    }
    responses: {
      /** @description 评论结果 */
      200: {
        content: {
          'application/json': components['schemas']['ResultCommentResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 添加文章
   * @description 添加文章
   */
  add_2: {
    /** @description 添加文章请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['AddArticleRequest']
      }
    }
    responses: {
      /** @description 文章 */
      200: {
        content: {
          '*/*': components['schemas']['ResultArticleResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 此用户申请添加指定用户为好友
   * @description 此用户申请添加指定用户为好友
   */
  apply: {
    parameters: {
      query: {
        /** @description 被申请用户id */
        toUserId: number
      }
    }
    responses: {
      /** @description 是否申请成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 验证手机验证码并登录
   * @description 验证手机验证码并登录
   */
  verify: {
    parameters: {
      query: {
        phone: string
        /** @description 验证码 */
        code: string
      }
    }
    responses: {
      /** @description 是否验证成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultVerificationResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 用户微信登录
   * @description 用户微信登录
   */
  login: {
    parameters: {
      query: {
        /** @description 微信code */
        code: string
      }
    }
    responses: {
      /** @description 登录结果 */
      200: {
        content: {
          '*/*': components['schemas']['ResultLoginResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取用户信息
   * @description 获取用户信息
   */
  info: {
    responses: {
      /** @description 用户信息 */
      200: {
        content: {
          '*/*': components['schemas']['ResultUser']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取指定id的用户信息
   * @description 获取指定id的用户信息
   */
  info_1: {
    parameters: {
      query: {
        /** @description 用户id */
        id: number
      }
    }
    responses: {
      /** @description 用户信息 */
      200: {
        content: {
          '*/*': components['schemas']['ResultUser']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 检查登录态
   * @description 检查登录态
   */
  check: {
    responses: {
      /** @description 是否登录且token有效 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 用户手机号登录
   * @description 用户手机号登录
   */
  authLogin: {
    parameters: {
      query: {
        /** @description authCode 验证验证码的时候获取的code */
        code: string
      }
    }
    responses: {
      /** @description 登录结果 */
      200: {
        content: {
          '*/*': components['schemas']['ResultLoginResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  hello: {
    responses: {
      /** @description OK */
      200: {
        content: never
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  test502: {
    responses: {
      /** @description OK */
      200: {
        content: never
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  test500: {
    responses: {
      /** @description OK */
      200: {
        content: never
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  test404: {
    responses: {
      /** @description OK */
      200: {
        content: never
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  test403: {
    responses: {
      /** @description OK */
      200: {
        content: never
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  test401: {
    responses: {
      /** @description OK */
      200: {
        content: never
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  test400: {
    responses: {
      /** @description OK */
      200: {
        content: never
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  test200: {
    responses: {
      /** @description OK */
      200: {
        content: never
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取章节
   * @description 获取章节
   */
  getSection: {
    parameters: {
      query: {
        /** @description 问卷ID */
        surveyId: number
      }
    }
    responses: {
      /** @description 章节列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListSection']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取选项
   * @description 获取选项
   */
  getOption: {
    parameters: {
      query: {
        /** @description 问题ID */
        issueId: number
      }
    }
    responses: {
      /** @description 选项列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListOptions']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取问题
   * @description 获取问题
   */
  getIssue: {
    parameters: {
      query: {
        /** @description 章节ID */
        sectionId: number
      }
    }
    responses: {
      /** @description 问题列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListIssue']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取问卷
   * @description 获取问卷
   */
  get: {
    responses: {
      /** @description 问卷列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListSurvey']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取建议列表
   * @description 获取建议列表
   */
  getSuggestions: {
    parameters: {
      query: {
        /** @description 类型 1意见反馈 2政策建议 */
        type: number
        /** @description 页码 */
        page: number
        /** @description 每页数量 */
        pageSize: number
      }
    }
    responses: {
      /** @description 意见反馈列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListSuggestion']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 根据关键词搜索用户
   * @description 根据关键词搜索用户
   */
  getUserList: {
    parameters: {
      query: {
        /** @description 页码 */
        page: number
        /** @description 页大小 */
        pageSize: number
        /** @description 关键词 */
        keyword: string
      }
    }
    responses: {
      /** @description 用户列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListBriefUserResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 根据关键词搜索帖子
   * @description 根据关键词搜索帖子
   */
  getPosts: {
    parameters: {
      query: {
        /** @description 页码 */
        page: number
        /** @description 页大小 */
        pageSize: number
        /** @description 关键词 */
        keyword: string
      }
    }
    responses: {
      /** @description 帖子列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListPostResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 根据关键词搜索好友的帖子
   * @description 根据关键词搜索好友的帖子
   */
  getFriendsPosts: {
    parameters: {
      query: {
        /** @description 页码 */
        page: number
        /** @description 页大小 */
        pageSize: number
        /** @description 关键词 */
        keyword: string
      }
    }
    responses: {
      /** @description 帖子列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListPostResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  getArticles: {
    parameters: {
      query: {
        page: number
        pageSize: number
        keyword: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['ResultListArticleResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取问卷作答结果
   * @description 获取问卷作答结果
   */
  getResult: {
    parameters: {
      query: {
        /** @description 问卷作答记录 ID */
        responseId: number
      }
    }
    responses: {
      /** @description 问卷作答结果 */
      200: {
        content: {
          '*/*': components['schemas']['ResultResultResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取当前用户正在作答的问卷记录
   * @description 获取当前用户正在作答的问卷记录
   */
  getResponse: {
    responses: {
      /** @description 问卷作答记录 */
      200: {
        content: {
          '*/*': components['schemas']['ResultSurveyData']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取问卷包含的所有章节
   * @description 获取问卷包含的所有章节
   */
  get_1: {
    parameters: {
      query: {
        /** @description 问卷 ID */
        surveyId: number
      }
    }
    responses: {
      /** @description 问卷 */
      200: {
        content: {
          '*/*': components['schemas']['ResultSurveyResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取用户最近已完成的问卷作答记录
   * @description 获取用户最近已完成的问卷作答记录
   */
  getLatest: {
    responses: {
      /** @description 问卷作答记录 */
      200: {
        content: {
          '*/*': components['schemas']['ResultSurveyData']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取章节包含的问题+选项列表
   * @description 获取章节包含的问题+选项列表
   */
  get_2: {
    parameters: {
      query: {
        /** @description 章节 ID */
        sectionId: number
        /** @description 页码 */
        page: number
        /** @description 每页大小 */
        pageSize: number
      }
    }
    responses: {
      /** @description 问题+选项列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListIssueResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取用户的所有已完成的问卷作答记录
   * @description 获取用户的所有已完成的问卷作答记录
   */
  getSurveyData: {
    responses: {
      /** @description 问卷作答记录列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListSurveyData']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取回复列表
   * @description 获取回复列表
   */
  getList: {
    parameters: {
      query: {
        /** @description 页码 */
        page: number
        /** @description 页大小 */
        pageSize: number
        /** @description 评论id */
        commentId: number
      }
    }
    responses: {
      /** @description 回复列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListReplyResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取好友列表
   * @description 获取好友列表
   */
  getFriendList: {
    parameters: {
      query: {
        /** @description 页码 */
        page: number
        /** @description 页大小 */
        pageSize: number
      }
    }
    responses: {
      /** @description 好友列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListBriefFriendResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 问答搜索
   *  输入用户提问的句子，返回包含关键词的问题列表，如果没有找到关键词则返回空列表
   * @description 问答搜索
   *  输入用户提问的句子，返回包含关键词的问题列表，如果没有找到关键词则返回空列表
   */
  get_3: {
    parameters: {
      query: {
        /** @description 用户提问的句子 */
        sentence: string
      }
    }
    responses: {
      /** @description 包含关键词的问题列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListQuestion']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取随机问题
   *  猜你想问？
   * @description 获取随机问题
   *  猜你想问？
   */
  getRand: {
    responses: {
      /** @description 随机问题列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListQuestion']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取问答全部内容
   * @description 获取问答全部内容
   */
  getDetail: {
    parameters: {
      query: {
        /** @description 问题 ID */
        id: number
      }
    }
    responses: {
      /** @description 问答全部内容 */
      200: {
        content: {
          '*/*': components['schemas']['ResultQuestion']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取帖子列表
   * @description 获取帖子列表
   */
  getList_1: {
    parameters: {
      query: {
        /** @description 页码 */
        page: number
        /** @description 页大小 */
        pageSize: number
        /** @description 是否按照热度排序 */
        orderByPopularity: boolean
      }
    }
    responses: {
      /** @description 帖子列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListPostResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取好友的帖子列表
   * @description 获取好友的帖子列表
   */
  getFriendsPost: {
    parameters: {
      query: {
        /** @description 页码 */
        page: number
        /** @description 页大小 */
        pageSize: number
      }
    }
    responses: {
      /** @description 好友的帖子列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListPostResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取帖子详情
   * @description 获取帖子详情
   */
  getDetail_1: {
    parameters: {
      query: {
        /** @description 帖子id */
        postId: number
      }
    }
    responses: {
      /** @description 帖子详情 */
      200: {
        content: {
          '*/*': components['schemas']['ResultPostResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取指定用户的帖子列表
   *  用于查看个人主页
   * @description 获取指定用户的帖子列表
   *  用于查看个人主页
   */
  getByUser: {
    parameters: {
      query: {
        /** @description 用户id */
        userId: number
        /** @description 页码 */
        page: number
        /** @description 页大小 */
        pageSize: number
      }
    }
    responses: {
      /** @description 用户的帖子 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListBriefPostResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取指定好友消息列表
   * @description 获取指定好友消息列表
   */
  get_4: {
    parameters: {
      query: {
        /** @description 好友 ID */
        friendId: number
        /** @description 页码 */
        page: number
        /** @description 每页大小 */
        pageSize: number
      }
    }
    responses: {
      /** @description 消息列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListMessageResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取简要常见问题
   * @description 获取简要常见问题
   */
  getSuggestions_1: {
    parameters: {
      query: {
        /** @description 页码 */
        page: number
        /** @description 每页数量 */
        pageSize: number
      }
    }
    responses: {
      /** @description 简要常见问题列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListBriefHelpResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取常见问题详情
   * @description 获取常见问题详情
   */
  getDetail_2: {
    parameters: {
      query: {
        /** @description 帮助id */
        id: number
      }
    }
    responses: {
      /** @description 帮助详情 */
      200: {
        content: {
          '*/*': components['schemas']['ResultHelp']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取评论列表
   * @description 获取评论列表
   */
  getList_2: {
    parameters: {
      query: {
        /** @description 页码 */
        page: number
        /** @description 页大小 */
        pageSize: number
        /** @description 帖子/文章id */
        objId: number
        /** @description 类型 */
        type: number
      }
    }
    responses: {
      /** @description 评论列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListCommentResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取评论详情
   * @description 获取评论详情
   */
  getDetail_3: {
    parameters: {
      query: {
        /** @description 评论id */
        commentId: number
        /** @description 类型 */
        type: number
      }
    }
    responses: {
      /** @description 评论详情 */
      200: {
        content: {
          '*/*': components['schemas']['ResultCommentResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取文章列表
   * @description 获取文章列表
   */
  getList_3: {
    parameters: {
      query: {
        /** @description 页码 */
        page: number
        /** @description 页大小 */
        pageSize: number
        /** @description 文章类型 1每日新政 2规划指南 3投资教育 4行业动态 5研究报告 6消费者权益保护 */
        type: number
      }
    }
    responses: {
      /** @description 文章列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListArticleResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 获取好友申请列表
   * @description 获取好友申请列表
   */
  getApplyList: {
    parameters: {
      query: {
        /** @description 页码 */
        page: number
        /** @description 页大小 */
        pageSize: number
      }
    }
    responses: {
      /** @description 申请列表 */
      200: {
        content: {
          '*/*': components['schemas']['ResultListApplyDto']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 删除用户
   * @description 删除用户
   */
  deleteUser: {
    responses: {
      /** @description 删除结果 */
      200: {
        content: {
          '*/*': components['schemas']['ResultInteger']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 删除章节
   * @description 删除章节
   */
  delSection: {
    parameters: {
      query: {
        /** @description 章节ID */
        id: number
      }
    }
    responses: {
      /** @description 是否成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 删除选项
   * @description 删除选项
   */
  delOption: {
    parameters: {
      query: {
        /** @description 选项ID */
        id: number
      }
    }
    responses: {
      /** @description 是否成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 删除问题
   * @description 删除问题
   */
  delIssue: {
    parameters: {
      query: {
        /** @description 问题ID */
        id: number
      }
    }
    responses: {
      /** @description 是否成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 删除问卷
   * @description 删除问卷
   */
  del: {
    parameters: {
      query: {
        /** @description 问卷ID */
        id: number
      }
    }
    responses: {
      /** @description 是否成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 删除回复
   * @description 删除回复
   */
  delReply: {
    parameters: {
      query: {
        /** @description 回复id */
        replyId: number
      }
    }
    responses: {
      /** @description 是否删除成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 删除好友
   * @description 删除好友
   */
  deleteFriend: {
    parameters: {
      query: {
        /** @description 好友id */
        friendId: number
      }
    }
    responses: {
      /** @description 是否删除成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 删除帖子
   * @description 删除帖子
   */
  delete: {
    parameters: {
      query: {
        /** @description 帖子id */
        postId: number
      }
    }
    responses: {
      /** @description 数据库修改是否成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 删除消息
   * @description 删除消息
   */
  delete_1: {
    parameters: {
      query: {
        /** @description 消息 ID */
        id: number
      }
    }
    responses: {
      /** @description 是否删除成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 取消点赞
   * @description 取消点赞
   */
  unlike: {
    /** @description 取消点赞请求 */
    requestBody: {
      content: {
        'application/json': components['schemas']['DoLikeRequest']
      }
    }
    responses: {
      /** @description 是否取消点赞成功 */
      200: {
        content: {
          'application/json': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
  /**
   * 删除评论
   * @description 删除评论
   */
  delete_2: {
    parameters: {
      query: {
        /** @description 评论id */
        commentId: number
      }
    }
    responses: {
      /** @description 数据库修改是否成功 */
      200: {
        content: {
          '*/*': components['schemas']['ResultBoolean']
        }
      }
      /** @description Internal Server Error */
      500: {
        content: {
          '*/*': components['schemas']['ResultObject']
        }
      }
    }
  }
}
